name: Docker Image CI

on:
  workflow_dispatch:
  
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set Image tag
      run: |
          echo "IMAGE_TAG=$(date +%s)" >> $GITHUB_ENV

          
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag ghcr.io/dominate2/webtest4azura:$IMAGE_TAG --tag ghcr.io/dominate2/webtest4azura:latest
        docker login ghcr.io -u dominate2 -p ${{secrets.GHCR_TOKEN}}
        docker push ghcr.io/dominate2/webtest4azura:$IMAGE_TAG
        docker push ghcr.io/dominate2/webtest4azura:latest

    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'teszt-13A'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_7d454ee9d856439ab1ba71dd2d3bf245 }}
        images: 'ghcr.io/dominate2/webtest4azura:${{ env.IMAGE_TAG }}'
